spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/management
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace

jwt:
  secret: VlwEyVBsYt9V7zq57TejMnVUyzblYcfPQye08f7MGVA9XkHa

management:
  server:
    port: 8080
  endpoints:
    web:
      bash-path: /actuator
      exposure:
        include: "health,info,metrics,env"